application:
  security:
    jwt:
      secret: 5867a8374e7c0f6284b177b48faf89e1c79d72d8
      token-validity-in-seconds: 50000000
      refresh-token-validity-in-seconds: 500000
      token-validity-in-seconds-for-remember-me: 2592000

  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/signup

spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@127.0.0.1:1521:xe
    username: scott
    password: tiger

  devtools:
    livereload:
      enabled: true

  freemarker:
    cache: false

  jpa:
    hibernate:
      ddl-auto: create   #애플리케이션  실행시점에 내가가지고잇는 엔티티를지우고(테이블) 다시생성
    properties:
      hibernate:
        #show_sql: true    #엔 sout에 출력해서  안쓰는게좋다
        format_sql: true
        use_sql_comments : true #JPQL 보고싶다면
        default_batch_fetch_size: 100
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 147411542994-dl2a4f22ibpec19irv565t902b7v3nhg.apps.googleusercontent.com
            client-secret: rToTVL8jmx3xFqHiJr4d_tE6
            redirect-uri: http://localhost:8080/oauth2/callback/{registrationId}
            scope: #우리가 리소스 오너(구글)에게 요청하는 승낙받아야하는 사용하고자하는 기능을 스콥이라함
              - email
              - profile

          github:
            client-id: 72b04d1f8cb329b229cd
            client-secret: fd0163b71ff11d51e2f0ce5bc834093e6000606f
            redirect-uri: http://localhost:8080/oauth2/callback/{registrationId}


          kakao:
            client-id: 07c9a89123e46ae5f72c72e9e0423d02
            client-secret: MVQJF2zabDZwmSrcmiFBihUPmusj2cAu
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/oauth2/callback/{registrationId}

            scope:
              - profile
              - account_email

            client-authentication-method: POST
            client-name: kakao

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id


logging:
  level:
    org.hibernate.SQL: debug #logger 출력
    # org.hibernate.type: trace




